### ISSUE TITLE
[BUG] Go to source not working for Kotlin files (IntelliJ Idea 2024.1.4)

### ISSUE THREAD

**Issue by bwajtr** [vaadin/copilot#30]
### Description of the Bug

1. Using IntelliJ IDEA 2024.1.4 (Ultimate Edition)
2. Installed Vaadin plugin 1.0.9 - however Copilot reports that the plugin is not found (I've already created another bug for that)
3. Start the SprintBoot application by running the ApplicadtionMain class from within Idea
4. Activate Copilot
5. Right-clicked a component -> Go To Source
6. A Log in Idea shows only `[ERROR] c.v.c.ide.IdeIntegration Unable to find file null`

<img width="800" alt="image" src="https://github.com/user-attachments/assets/98dfa4e2-aec4-4f1a-8af3-a694f5bb765b">

### Expected Behavior

I'd expect to be navigated to the source code. Note that in Vaadin 24.3 I was using the feature "Find component in source" and it was working nicely (the logfile pointed me to a source code file) despite we are using Kotlin instead of Java in the project. Seems that the new feature is not Kotlin compatible?

### Versions
Hilla: 24.4.4
Flow: 24.4.4
Vaadin: 24.4.7
Copilot: 24.4.8
Copilot IDE Plugin: false
Java: Eclipse Adoptium 17.0.7
Java Hotswap: false
Frontend Hotswap: Disabled, using pre-built bundle
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Macintosh

**Comment by Artur-** [comment]
Could you retest this with the latest 24.5 alpha + the latest plugin version? A lot has changed since July

**Comment by sveinnetnordic** [comment]
> Could you retest this with the latest 24.5 alpha + the latest plugin version? A lot has changed since July

Flow 24.5.0.beta1
2024-09-25T13:18:41.027+02:00 ERROR 9952 --- [nio-8088-exec-9] com.vaadin.copilot.ide.IdeIntegration    : Unable to find file null

**Comment by bwajtr** [comment]
Flow `24.5.0.beta3`, still the same issue. However, the logs are now better and it seems that the Copilot is probably looking for `HelloWorldView.java` file, instead of the `HelloWorldView.kt` - as I said in the description, I'm using Kotlin instead of Java for rendering views (and I'll only repeat that the "Find components in source" in Vaadin 24.3 worked with the Kotlin codebase, so I see this as a regression).

Reproducible example here: https://github.com/bwajtr/vaadin-kotlin-maven-spring-boot

This is what the log shows now:
```
2024-09-27T08:49:40.435+02:00 ERROR 49267 --- [nio-8080-exec-5] com.vaadin.copilot.ide.IdeIntegration    : Unable to find file null2024-09-27T08:49:38.753+02:00 ERROR 49267 --- [io-8080-exec-10] c.v.copilot.plugins.i18n.I18nHandler     : Failed to get translatable properties

java.nio.file.NoSuchFileException: /Users/wajtr/Developer/temp/vaadin-kotlin-maven/src/main/java/org/wajtr/experiments/vaadinkotlin/HelloWorldView.java
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432) ~[na:na]
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[na:na]
	at java.base/java.nio.file.Files.newInputStream(Files.java:160) ~[na:na]
	at org.apache.commons.io.FileUtils.lambda$readFileToString$12(FileUtils.java:2698) ~[commons-io-2.17.0.jar:2.17.0]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:3223) ~[commons-io-2.17.0.jar:2.17.0]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:3198) ~[commons-io-2.17.0.jar:2.17.0]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2698) ~[commons-io-2.17.0.jar:2.17.0]
	at com.vaadin.copilot.ProjectManager.readFile(ProjectManager.java:56) ~[copilot-24.5.0.beta2.jar:na]
	at com.vaadin.copilot.plugins.i18n.I18nHandler.handleGetTranslatableProperties(I18nHandler.java:242) ~[copilot-24.5.0.beta2.jar:na]
	at com.vaadin.copilot.plugins.i18n.I18nHandler.handleMessage(I18nHandler.java:130) ~[copilot-24.5.0.beta2.jar:na]
	at com.vaadin.copilot.Copilot.handleMessage(Copilot.java:139) ~[copilot-24.5.0.beta2.jar:na]
	at com.vaadin.base.devserver.DebugWindowConnection.onMessage(DebugWindowConnection.java:336) ~[vaadin-dev-server-24.5.0.beta2.jar:na]
	at com.vaadin.flow.server.communication.PushHandler.handleDebugWindowMessage(PushHandler.java:668) ~[flow-server-24.5.0.beta2.jar:24.5.0.beta2]
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:235) ~[flow-server-24.5.0.beta2.jar:24.5.0.beta2]
	at com.vaadin.flow.server.communication.PushHandler.onMessage(PushHandler.java:644) ~[flow-server-24.5.0.beta2.jar:24.5.0.beta2]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:90) ~[flow-server-24.5.0.beta2.jar:24.5.0.beta2]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:79) ~[flow-server-24.5.0.beta2.jar:24.5.0.beta2]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.lambda$dispatch$2(DefaultWebSocketProcessor.java:326) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:323) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:428) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.JSR356Endpoint.lambda$onOpen$2(JSR356Endpoint.java:261) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:130) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:484) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:284) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-09-27T08:49:40.435+02:00 ERROR 49267 --- [nio-8080-exec-5] com.vaadin.copilot.ide.IdeIntegration    : Unable to find file null
```

**Comment by sveinnetnordic** [comment]
Maybe wrong path is used like here: https://github.com/vaadin/intellij-plugin/issues/47

**Comment by MarcinVaadin** [comment]
In this issue it's a matter of Kotlin files. Fix will be done in Flow directly https://github.com/vaadin/flow/pull/20073.
