### ISSUE TITLE
[BUG] Copilot does not work with skeleton-starter-flow-cdi-24

### ISSUE THREAD

**Issue by TatuLund** [vaadin/copilot#48]
Copilot seems not to work with CDI based projects

### Description of the Bug

Attempting to edit UI in Copilot results an exception:

```
ERROR [com.vaadin.copilot.javarewriter.ConstructorAnalyzer] (default task-1) Unable to read class com.vaadin.flow.component.textfield.TextField: java.io.IOException: Class not found
at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//org.objectweb.asm.ClassReader.readStream(ClassReader.java:316)
at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//org.objectweb.asm.ClassReader.<init>(ClassReader.java:300)
at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.copilot.javarewriter.ConstructorAnalyzer.getMappingsForConstructor(ConstructorAnalyzer.java:119)

Expected to find an object creation expression such as "new MainView()" at C:\Users\xxxxxxxx\dev\Code\Training\vaadin\skeleton-starter-flow-cdi-24\src\main\java\org\jboss\weld\injection\ConstructorInjectionPoint.java:119 but found no line with number 119 as the file only has 53 lines
```

### Expected Behavior

A description of what you would expect to happen. (Sometimes it is clear what the expected outcome is if something does not work; other times, it is not super clear.)

### Minimal Reproducible Example

Use skeleton-starter-flow-cdi-24, try to edit the UI in Copilot

### Versions

- Vaadin Flow/Hilla Framework Version: e.g., 24.5

**Comment by Artur-** [comment]
Fixed in Vaadin 24.5.4
